# Generated by Django 5.2.5 on 2025-08-21 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(help_text='Machine hostname', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Machine IP address', null=True)),
                ('os_info', models.CharField(blank=True, help_text='Operating system information', max_length=255)),
                ('platform', models.CharField(blank=True, help_text='Platform (Windows, macOS, Linux)', max_length=50)),
                ('architecture', models.CharField(blank=True, help_text='System architecture (x86_64, arm64, etc.)', max_length=20)),
                ('cpu_count', models.IntegerField(blank=True, help_text='Number of CPU cores', null=True)),
                ('total_memory', models.BigIntegerField(blank=True, help_text='Total memory in bytes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the host is currently active')),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='When this host was first seen')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='When this host was last seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'db_table': 'hosts',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(help_text='Process ID')),
                ('ppid', models.IntegerField(blank=True, help_text='Parent Process ID', null=True)),
                ('name', models.CharField(help_text='Process name', max_length=255)),
                ('exe', models.CharField(blank=True, help_text='Executable path', max_length=500)),
                ('cmdline', models.TextField(blank=True, help_text='Command line arguments')),
                ('status', models.CharField(choices=[('running', 'Running'), ('sleeping', 'Sleeping'), ('disk-sleep', 'Disk Sleep'), ('stopped', 'Stopped'), ('zombie', 'Zombie'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('cpu_percent', models.FloatField(default=0.0, help_text='CPU usage percentage')),
                ('memory_rss', models.BigIntegerField(default=0, help_text='Resident Set Size in bytes')),
                ('memory_vms', models.BigIntegerField(default=0, help_text='Virtual Memory Size in bytes')),
                ('memory_percent', models.FloatField(default=0.0, help_text='Memory usage percentage')),
                ('create_time', models.FloatField(blank=True, help_text='Process creation time (timestamp)', null=True)),
                ('num_threads', models.IntegerField(blank=True, help_text='Number of threads', null=True)),
                ('nice', models.IntegerField(blank=True, help_text='Process nice value', null=True)),
                ('username', models.CharField(blank=True, help_text='Username running the process', max_length=100)),
                ('working_set', models.BigIntegerField(blank=True, help_text='Working set size (Windows)', null=True)),
                ('private_bytes', models.BigIntegerField(blank=True, help_text='Private bytes (Windows)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'db_table': 'processes',
                'ordering': ['-cpu_percent', '-memory_percent'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was taken')),
                ('total_processes', models.IntegerField(help_text='Total number of processes in this snapshot')),
                ('total_cpu_percent', models.FloatField(default=0.0, help_text='Total CPU usage percentage')),
                ('total_memory_mb', models.FloatField(default=0.0, help_text='Total memory usage in MB')),
                ('system_cpu_percent', models.FloatField(blank=True, help_text='System CPU usage percentage', null=True)),
                ('system_memory_percent', models.FloatField(blank=True, help_text='System memory usage percentage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='process_api.host')),
            ],
            options={
                'verbose_name': 'Process Snapshot',
                'verbose_name_plural': 'Process Snapshots',
                'db_table': 'process_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='process_api.process')),
                ('parent_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='process_api.process')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='process_api.processsnapshot')),
            ],
            options={
                'verbose_name': 'Process Relationship',
                'verbose_name_plural': 'Process Relationships',
                'db_table': 'process_relationships',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='process_api.processsnapshot'),
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_count', models.IntegerField(help_text='Number of CPU cores')),
                ('cpu_freq_current', models.FloatField(blank=True, help_text='Current CPU frequency in MHz', null=True)),
                ('cpu_freq_min', models.FloatField(blank=True, help_text='Minimum CPU frequency in MHz', null=True)),
                ('cpu_freq_max', models.FloatField(blank=True, help_text='Maximum CPU frequency in MHz', null=True)),
                ('memory_total', models.BigIntegerField(help_text='Total memory in bytes')),
                ('memory_available', models.BigIntegerField(help_text='Available memory in bytes')),
                ('memory_used', models.BigIntegerField(help_text='Used memory in bytes')),
                ('memory_free', models.BigIntegerField(help_text='Free memory in bytes')),
                ('memory_percent', models.FloatField(help_text='Memory usage percentage')),
                ('disk_usage', models.JSONField(default=dict, help_text='Disk usage information')),
                ('network_io', models.JSONField(default=dict, help_text='Network I/O statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_metrics', to='process_api.host')),
            ],
            options={
                'verbose_name': 'System Metrics',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='processsnapshot',
            index=models.Index(fields=['host', '-timestamp'], name='process_sna_host_id_ceadf0_idx'),
        ),
        migrations.AddIndex(
            model_name='processsnapshot',
            index=models.Index(fields=['timestamp'], name='process_sna_timesta_2186e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processrelationship',
            unique_together={('snapshot', 'parent_process', 'child_process')},
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['snapshot', 'pid'], name='processes_snapsho_0a60b2_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['snapshot', 'ppid'], name='processes_snapsho_1b50ed_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['name'], name='processes_name_01eacd_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['status'], name='processes_status_b87a18_idx'),
        ),
    ]
